name: Docker Image CI

on:
  push:
    branches: 
      - main

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - 
      name: Checkout
      uses: actions/checkout@v2

    - 
      name: Set up QEMU
      uses: docker/setup-qemu-action@v1

    - 
      name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v1

    -
      name: Login to DockerHub
      uses: docker/login-action@v1 
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}

    -
      name: Build and push
      run: |
          IMAGE_ID=ghcr.io/${{ github.repository }}/$IMAGE_NAME

          # Change all uppercase to lowercase
          IMAGE_ID=$(echo $IMAGE_ID | tr '[A-Z]' '[a-z]')
          
          # Strip git ref prefix from version
          VERSION=$(echo "${{ github.ref }}" | sed -e 's,.*/\(.*\),\1,')
        
          # Use Docker `latest` tag convention
          [ "$VERSION" == "main" ] && VERSION=latest

          echo IMAGE_ID=$IMAGE_ID
          echo VERSION=$VERSION

          # Build and Publish container image
          docker buildx build --push \
          --tag kdtheory/pycryptobot-dockerhub:latest \
          --platform linux/armhf,linux/aarch64,linux/amd64 \
          --file Dockerfile .

